reddit/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('create/', views.create_post, name='create_post'),
    path('<int:post_id>/', views.view_post, name='view_post'),
    path('edit/<int:post_id>/', views.edit_post, name='edit_post'),
    path('post/<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('vote/', views.vote_post, name='vote_post'),

]

reddit/reddit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reddit_users.urls', namespace='reddit_users')),
    path('subreddits/', include('subreddits.urls', namespace='subreddits')),
    path('posts/', include('posts.urls', namespace='posts')),
]

reddit/reddit_users/urls.py
from django.urls import path
from . import views

app_name = 'reddit_users'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<str:username>/', views.view_profile, name='view_profile'),
    path('profile/<str:username>/follow/',
         views.follow_user, name='follow_user'),
    path('profile/<str:username>/unfollow/',
         views.unfollow_user, name='unfollow_user'),
    path('search/', views.search, name='search')
]

reddit/subreddits/urls.py
from django.urls import path
from . import views

app_name = 'subreddits'

urlpatterns = [
    path('create/', views.create_subreddit, name='create_subreddit'),
    path('<int:subreddit_id>/', views.view_subreddit, name='view_subreddit')

]

reddit/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from subreddits.models import Subreddit


# Create your models here.
# Post model

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='posts')
    subreddit = models.ForeignKey(
        Subreddit, on_delete=models.CASCADE, related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    upvoted_by = models.ManyToManyField(User, related_name='upvoted_posts')
    downvoted_by = models.ManyToManyField(User, related_name='downvoted_posts')

    def __str__(self):
        return self.title

    def get_vote_count(self):
        return self.upvoted_by.count() - self.downvoted_by.count()

    def upvote(self, user):
        if user in self.downvoted_by.all():
            self.downvoted_by.remove(user)
        if user in self.upvoted_by.all():
            self.upvoted_by.remove(user)
        else:
            self.upvoted_by.add(user)

    def downvote(self, user):
        if user in self.upvoted_by.all():
            self.upvoted_by.remove(user)
        if user in self.downvoted_by.all():
            self.downvoted_by.remove(user)
        else:
            self.downvoted_by.add(user)

reddit/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Post
from comments.models import Comment
from comments.forms import CommentForm
from subreddits.models import Subreddit
from django.http import JsonResponse
# Create your views here.


@login_required(login_url='/login/')
def create_post(request):
    if request.method == 'POST':
        title = request.POST['title']
        content = request.POST['content']
        subreddit_id = request.POST['subreddit']
        subreddit = get_object_or_404(Subreddit, pk=subreddit_id)
        post = Post(title=title, content=content,
                    author=request.user, subreddit=subreddit)
        post.save()
        messages.success(request, 'Post created successfully')
        return redirect('subreddits:view_subreddit', subreddit_id=subreddit_id)
    else:
        subreddit_id = request.GET.get('subreddit')
        subreddit = get_object_or_404(Subreddit, pk=subreddit_id)

        return render(request, 'posts/create_post.html', {'subreddit': subreddit})


def view_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    if request.user.is_authenticated:
        if request.method == 'POST':
            content = request.POST.get('content')
            parent_comment_id = request.POST.get('parent_comment_id')
            parent_comment = None

            if parent_comment_id:
                parent_comment = get_object_or_404(
                    Comment, id=parent_comment_id)

            # Edit or delete comment
            if 'edit_comment_id' in request.POST:
                comment_id = request.POST['edit_comment_id']
                comment = get_object_or_404(Comment, id=comment_id)
                if request.user == comment.author:
                    form = CommentForm(request.POST, instance=comment)
                    if form.is_valid():
                        form.save()
                        return redirect('posts:view_post', post_id=post.id)
            elif 'delete_comment_id' in request.POST:
                comment_id = request.POST['delete_comment_id']
                comment = get_object_or_404(Comment, id=comment_id)
                if request.user == comment.author:
                    comment.delete()
                    return redirect('posts:view_post', post_id=post.id)

            if content:
                Comment.objects.create(
                    post=post,
                    author=request.user,
                    content=content,
                    parent_comment=parent_comment
                )
                messages.success(request, 'Comment added successfully')
            else:
                messages.error(request, 'Text field cannot be empty')

            return redirect('posts:view_post', post_id=post_id)

        # This block is moved outside the POST check to be accessible for GET requests as well
        comments = Comment.objects.filter(post=post, parent_comment__isnull=True).select_related(
            'author').prefetch_related('replies')
        return render(request, 'posts/view_post.html', {'post': post, 'comments': comments})

    # For unauthenticated users
    else:
        comments = Comment.objects.filter(post=post, parent_comment__isnull=True).select_related(
            'author').prefetch_related('replies')
        return render(request, 'posts/view_post.html', {'post': post})


@login_required(login_url='/login/')
def edit_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.user != post.author:
        messages.error(request, 'You are not authorized to edit this post.')
        return redirect('posts:view_post', post_id=post_id)

    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')

        if title and content:
            post.title = title
            post.content = content
            post.save()
            messages.success(request, 'Post updated successfully')
            return redirect('posts:view_post', post_id=post_id)
        else:
            messages.error(request, 'Both title and content are required.')

    return render(request, 'posts/edit_post.html', {'post': post})


@login_required(login_url='/login/')
def delete_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.user != post.author:
        messages.error(request, 'You are not authorized to delete this post.')
        return redirect('posts:view_post', post_id=post_id)

    post.delete()
    messages.success(request, 'Post deleted successfully')
    return redirect('subreddits:view_subreddit', subreddit_id=post.subreddit.id)


@login_required(login_url='/login/')
def upvote_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.upvote(request.user)
    post.save()
    return JsonResponse({'vote_count': post.get_vote_count()})


@login_required(login_url='/login/')
def downvote_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.downvote(request.user)
    post.save()
    return JsonResponse({'vote_count': post.get_vote_count()})


@login_required(login_url='/login/')
def vote_post(request):
    post_id = request.POST.get('post_id')
    action = request.POST.get('action')
    post = get_object_or_404(Post, pk=post_id)
    if action == 'upvote':
        post.upvote(request.user)
    elif action == 'downvote':
        post.downvote(request.user)
    post.save()
    return JsonResponse({'vote_count': post.get_vote_count()})

reddit/posts/templates/posts/create_post.html
{% extends 'base.html' %}
<!-- loading static after extending base -->
{% load static %}
<!-- loading static  -->
{% block title %}Create Post{%endblock %}
<!-- title -->
{% block content %}
<div class="create-post-container">
  <h1>Create a new post in {{ subreddit.name }}</h1>
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="subreddit" value="{{ subreddit.id }}" />
    <div class="form-group">
      <label for="title">Title:</label>
      <input type="text" id="title" name="title" required />
    </div>
    <div class="form-group">
      <label for="content">Content:</label>
      <textarea id="content" name="content" required></textarea>
    </div>
    <button type="submit">Create Post +</button>
  </form>
</div>

{% endblock %}

reddit/posts/templates/posts/edit_post.html
{% extends 'base.html' %}
<!-- extending the base html format -->
{% load static %}
<!-- inheriting the css styling from base.css -->
{% block title %}Edit Post - Reddit Clone{% endblock %}
<!-- setting the main content -->
{% block content %}
<div class="edit-post-container">
  <h1>Edit Post</h1>
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="title">Title:</label>
      <input
        type="text"
        id="title"
        name="title"
        value="{{ post.title }}"
        required
      />
    </div>
    <div class="form-group">
      <label for="content">Content:</label>
      <textarea id="content" name="content" required>
{{ post.content }}</textarea
      >
    </div>
    <button type="submit">Save Changes</button>
  </form>
</div>
{% endblock %}

reddit/posts/templates/posts/view_post.html
{% extends 'base.html' %} {% load static %} {% block title %}{{ post.title }} -
Reddit Clone{% endblock %} {% block content %}
<div class="post-container">
  <div class="edit-message">
    {% for message in messages %}
    <h4>{{ message }}</h4>
    {% endfor %}
  </div>
  <style>
    .edit-message {
      margin-bottom: 1rem;
    }
    h4 {
      color: green;
    }
    .comment {
      margin-bottom: 1.5rem;
      padding-left: 1rem;
    }
    .replies {
      margin-left: 2rem;
      border-left: 2px solid #ccc;
      padding-left: 1rem;
    }
    .reply {
      margin-bottom: 1rem;
      padding-left: 1rem;
    }
    .reply-link {
      cursor: pointer;
      color: #ff4500;
      text-decoration: underline;
    }
  </style>
  <div class="post-header">
    <h2>{{ post.title }}</h2>
    <div class="post-details">
      <small
        ><a href="{% url 'reddit_users:view_profile' post.author.username %}"
          >u/{{ post.author.username }}</a
        >
        | {{ post.created_at }}</small
      >
      <span>
        in
        <a href="{% url 'subreddits:view_subreddit' post.subreddit.id %}">
          r/{{ post.subreddit.name }}</a
        >
      </span>
    </div>
  </div>
  <div class="post-body">
    <p>{{ post.content }}</p>
  </div>
  <div class="post-footer">
    <button
      class="vote-btn upvote-btn {% if request.user in post.upvoted_by.all %}upvoted{% endif %}"
      data-post-id="{{ post.id }}"
      style="border: none; background: none; cursor: pointer; outline: none"
    >
      <i class="bi bi-arrow-up-square"></i>
    </button>
    | <span id="vote-count-{{ post.id }}">{{ post.get_vote_count }}</span> |
    <button
      class="vote-btn downvote-btn {% if request.user in post.downvoted_by.all %}downvoted{% endif %}"
      data-post-id="{{ post.id }}"
      style="border: none; background: none; cursor: pointer; outline: none"
    >
      <i class="bi bi-arrow-down-square"></i>
    </button>
    {% if user == post.author %}
    <a href="{% url 'posts:edit_post' post.id %}">Edit</a> |
    <a href="#" id="delete-post-btn">Delete</a>
    {% endif %}
  </div>
  <br />
  <br />
  <br />
  <div class="make-comment-container">
    <form method="post" action="{% url 'posts:view_post' post.id %}">
      {% csrf_token %}
      <textarea
        name="content"
        rows="4"
        cols="50"
        id="comment-content"
        required
      ></textarea>
      <br />
      <button type="submit">Post Comment</button>
    </form>
  </div>
  <div class="comments-container">
    <h3>Comments</h3>
    {% for comment in comments %}
    <div class="comment">
      <small
        ><a href="{% url 'reddit_users:view_profile' user.username %}"
          >u/{{ comment.author.username }}</a
        >
        | {{ comment.created_at }}</small
      >
      <p>{{ comment.content }}</p>
      {% if comment.author == request.user %}
      <a
        href="#"
        class="edit-comment-link"
        data-comment-id="{{ comment.id }}"
        data-comment-content="{{ comment.content }}"
        >Edit</a
      >
      |
      <a href="#" class="delete-comment-link" data-comment-id="{{ comment.id }}"
        >Delete</a
      >
      | {% endif %}
      <a href="#" class="reply-link" data-comment-id="{{ comment.id }}"
        >Reply to comment</a
      >
      <div class="replies">
        {% include 'partials/replies.html' with replies=comment.replies.all %}
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<!-- Delete Post Modal -->
<div id="deleteModal" class="modal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <h2>Delete Post</h2>
    <p>Are you sure you want to delete the post "{{ post.title }}"?</p>
    <form method="post" action="{% url 'posts:delete_post' post.id %}">
      {% csrf_token %}
      <button type="submit" class="delete-btn">Delete</button>
      <button type="button" class="cancel-btn" id="cancel-delete-btn">
        Cancel
      </button>
    </form>
  </div>
</div>

<!-- Reply Post Modal -->
<div id="replyModal" class="modal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <form id="replyForm" method="post">
      {% csrf_token %}
      <textarea name="content" rows="4" cols="50" required></textarea>
      <input type="hidden" name="parent_comment_id" id="comment-id" />
      <button type="submit">Post Reply</button>
    </form>
  </div>
</div>

<!-- Edit Comment Modal -->
<div id="editCommentModal" class="modal">
  <div class="modal-content">
    <span class="close" id="closeEditModal">&times;</span>
    <form
      method="POST"
      action="{% url 'posts:view_post' post.id %}"
      id="editCommentForm"
    >
      {% csrf_token %}
      <input type="hidden" name="edit_comment_id" id="editCommentId" />
      <h5>Edit Comment</h5>
      <textarea
        name="content"
        id="editCommentContent"
        class="form-control"
        rows="3"
      ></textarea>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" id="cancelEdit">
          Close
        </button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div>
    </form>
  </div>
</div>

<!-- Delete Comment Modal -->
<div id="deleteCommentModal" class="modal">
  <div class="modal-content">
    <span class="close" id="closeDeleteModal">&times;</span>
    <form
      method="POST"
      action="{% url 'posts:view_post' post.id %}"
      id="deleteCommentForm"
    >
      {% csrf_token %}
      <input type="hidden" name="delete_comment_id" id="deleteCommentId" />
      <h5>Delete Comment</h5>
      <p>Are you sure you want to delete this comment?</p>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" id="cancelDelete">
          Close
        </button>
        <button type="submit" class="btn btn-danger">Delete</button>
      </div>
    </form>
  </div>
</div>

<script>
  // upvote, downvote post
  document.querySelectorAll(".vote-btn").forEach((button) => {
    button.addEventListener("click", function () {
      const postId = this.getAttribute("data-post-id");
      const action = this.classList.contains("upvote-btn")
        ? "upvote"
        : "downvote";
      const url = "{% url 'posts:vote_post' %}";

      fetch(url, {
        method: "POST",
        headers: {
          "X-CSRFToken": "{{ csrf_token }}",
          "Content-Type": "application/x-www-form-urlencoded",
        },
        body: new URLSearchParams({ post_id: postId, action: action }),
      })
        .then((response) => response.json())
        .then((data) => {
          document.getElementById(`vote-count-${postId}`).innerText =
            data.vote_count;
          if (action === "upvote") {
            this.classList.toggle("upvoted");
            this.classList.remove("downvoted");
            document
              .querySelector(`.downvote-btn[data-post-id="${postId}"]`)
              .classList.remove("downvoted");
          } else {
            this.classList.toggle("downvoted");
            this.classList.remove("upvoted");
            document
              .querySelector(`.upvote-btn[data-post-id="${postId}"]`)
              .classList.remove("upvoted");
          }
        });
    });
  });

  //modal box for delete post
  let modal = document.getElementById("deleteModal");
  let btn = document.getElementById("delete-post-btn");
  let span = document.getElementsByClassName("close")[0];
  let cancelBtn = document.getElementById("cancel-delete-btn");

  btn.onclick = function () {
    modal.style.display = "block";
  };

  span.onclick = function () {
    modal.style.display = "none";
  };

  cancelBtn.onclick = function () {
    modal.style.display = "none";
  };
  window.onclick = function (event) {
    if (event.target == modal) {
      modal.style.display = "none";
    }
  };

  // modal box for reply to reply
  document.addEventListener("DOMContentLoaded", function () {
    let modal = document.getElementById("replyModal");
    let span = document.getElementsByClassName("close")[0];

    document.querySelectorAll(".reply-link").forEach(function (link) {
      link.onclick = function (event) {
        event.preventDefault();
        let commentId = this.getAttribute("data-comment-id");
        document.getElementById("comment-id").value = commentId;
        modal.style.display = "block";
      };
    });

    span.onclick = function () {
      modal.style.display = "none";
    };

    window.onclick = function (event) {
      if (event.target == modal) {
        modal.style.display = "none";
      }
    };
  });

  // modal box for edit comment
  document.addEventListener("DOMContentLoaded", function () {
    var editCommentModal = document.getElementById("editCommentModal");
    var deleteCommentModal = document.getElementById("deleteCommentModal");

    var closeEditModal = document.getElementById("closeEditModal");
    var closeDeleteModal = document.getElementById("closeDeleteModal");

    var cancelEdit = document.getElementById("cancelEdit");
    var cancelDelete = document.getElementById("cancelDelete");

    var editCommentLinks = document.querySelectorAll(".edit-comment-link");
    var deleteCommentLinks = document.querySelectorAll(".delete-comment-link");

    editCommentLinks.forEach(function (link) {
      link.addEventListener("click", function (event) {
        event.preventDefault();
        var commentId = this.getAttribute("data-comment-id");
        var commentContent = this.getAttribute("data-comment-content");

        document.getElementById("editCommentContent").value = commentContent;
        document.getElementById("editCommentId").value = commentId;

        editCommentModal.style.display = "block";
      });
    });

    deleteCommentLinks.forEach(function (link) {
      link.addEventListener("click", function (event) {
        event.preventDefault();
        var commentId = this.getAttribute("data-comment-id");

        document.getElementById("deleteCommentId").value = commentId;

        deleteCommentModal.style.display = "block";
      });
    });

    closeEditModal.onclick = function () {
      editCommentModal.style.display = "none";
    };

    closeDeleteModal.onclick = function () {
      deleteCommentModal.style.display = "none";
    };

    cancelEdit.onclick = function () {
      editCommentModal.style.display = "none";
    };

    cancelDelete.onclick = function () {
      deleteCommentModal.style.display = "none";
    };

    window.onclick = function (event) {
      if (event.target == editCommentModal) {
        editCommentModal.style.display = "none";
      }
      if (event.target == deleteCommentModal) {
        deleteCommentModal.style.display = "none";
      }
    };
  });
  //upvote and downvote comment

  // document.addEventListener("DOMContentLoaded", function () {
  //   // Function to get the CSRF token
  //   function getCookie(name) {
  //     let cookieValue = null;
  //     if (document.cookie && document.cookie !== "") {
  //       const cookies = document.cookie.split(";");
  //       for (let i = 0; i < cookies.length; i++) {
  //         const cookie = cookies[i].trim();
  //         if (cookie.substring(0, name.length + 1) === name + "=") {
  //           cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
  //           break;
  //         }
  //       }
  //     }
  //     return cookieValue;
  //   }

  //   const csrftoken = getCookie("csrftoken");

  //   // Upvote comment
  //   document.querySelectorAll(".upvote-btn").forEach(function (btn) {
  //     btn.onclick = function () {
  //       let commentId = this.getAttribute("data-comment-id");
  //       fetch(`/comments/${commentId}/upvote/`, {
  //         method: "POST",
  //         headers: {
  //           "X-CSRFToken": csrftoken,
  //           "Content-Type": "application/json",
  //         },
  //         body: JSON.stringify({}),
  //       })
  //         .then((response) => response.json())
  //         .then((data) => {
  //           document.getElementById(`vote-count-${commentId}`).innerText =
  //             data.vote_count;
  //         })
  //         .catch((error) => console.error("Error:", error));
  //     };
  //   });

  //   // Downvote comment
  //   document.querySelectorAll(".downvote-btn").forEach(function (btn) {
  //     btn.onclick = function () {
  //       let commentId = this.getAttribute("data-comment-id");
  //       fetch(`/comments/${commentId}/downvote/`, {
  //         method: "POST",
  //         headers: {
  //           "X-CSRFToken": csrftoken,
  //           "Content-Type": "application/json",
  //         },
  //         body: JSON.stringify({}),
  //       })
  //         .then((response) => response.json())
  //         .then((data) => {
  //           document.getElementById(`vote-count-${commentId}`).innerText =
  //             data.vote_count;
  //         })
  //         .catch((error) => console.error("Error:", error));
  //     };
  //   });
  // });
</script>
{% endblock %}