reddit/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('create/', views.create_post, name='create_post'),
    path('<int:post_id>/', views.view_post, name='view_post'),
    path('edit/<int:post_id>/', views.edit_post, name='edit_post'),
    path('post/<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('vote/', views.vote_post, name='vote_post'),

]

reddit/reddit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reddit_users.urls', namespace='reddit_users')),
    path('subreddits/', include('subreddits.urls', namespace='subreddits')),
    path('posts/', include('posts.urls', namespace='posts')),
]

reddit/reddit_users/urls.py
from django.urls import path
from . import views

app_name = 'reddit_users'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<str:username>/', views.view_profile, name='view_profile'),
    path('profile/<str:username>/follow/',
         views.follow_user, name='follow_user'),
    path('profile/<str:username>/unfollow/',
         views.unfollow_user, name='unfollow_user'),
    path('search/', views.search, name='search')
]

reddit/subreddits/urls.py
from django.urls import path
from . import views

app_name = 'subreddits'

urlpatterns = [
    path('create/', views.create_subreddit, name='create_subreddit'),
    path('<int:subreddit_id>/', views.view_subreddit, name='view_subreddit')

]

reddit/reddit_users/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.

User = get_user_model()


class RedditUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    id_user = models.IntegerField(max_length=10)
    password = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self):
        return self.user.username

reddit/reddit_users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, auth
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import RedditUser
from posts.models import Post
from comments.models import Comment
from follow.models import Follow
from subreddits.models import Subreddit
from django.http import JsonResponse
from django.db.models import Q


# Create your views here.


def index(request):
    posts = Post.objects.all().order_by('-created_at')
    return render(request, 'reddit_users/homepage.html', {'posts': posts})


def follower_count(username):
    user = get_object_or_404(User, username=username)
    followers = Follow.objects.filter(following=user).count()
    return followers


def following_count(username):
    user = get_object_or_404(User, username=username)
    following = Follow.objects.filter(follower=user).count()
    return following


def view_profile(request, username):
    user = get_object_or_404(User, username=username)
    reddit_user = get_object_or_404(RedditUser, user=user)
    posts = Post.objects.filter(author=user).order_by('-created_at')
    comments = Comment.objects.filter(author=user).order_by('-created_at')
    post_count = posts.count()
    comment_count = Comment.objects.filter(author=user).count()
    is_following = Follow.objects.filter(
        follower=request.user, following=user).exists() if request.user.is_authenticated else False
    count_following = following_count(username=user.username)
    count_follower = follower_count(username=user.username)
    return render(request, 'reddit_users/profile.html', {
        'reddit_user': reddit_user,
        'posts': posts,
        'comments': comments,
        'profile_user': user,
        'post_count': post_count,
        'comment_count': comment_count,
        'is_following': is_following,
        'following_count': count_following,
        'follower_count': count_follower
    })


@login_required(login_url='/login/')
def follow_user(request, username):
    user_to_follow = get_object_or_404(User, username=username)
    follow, created = Follow.objects.get_or_create(
        follower=request.user, following=user_to_follow)
    if created:
        messages.info(request, f'You are now following {user_to_follow}')
    else:
        follow.delete()
        messages.info(request, f'You are no longer following {user_to_follow}')

    return redirect('reddit_users:view_profile', username=username)


@login_required(login_url='/login/')
def unfollow_user(request, username):
    user_to_unfollow = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(
        follower=request.user, following=user_to_unfollow).delete()
    messages.info(request, f'You are no longer following {user_to_unfollow}')

    return redirect('reddit_users:view_profile', username=username)


def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        password2 = request.POST['password2']
        email = request.POST['email']

        if password == password2:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'Username taken')
                return render(request, 'reddit_users/signup.html')

            elif User.objects.filter(email=email).exists():
                messages.info(request, 'Email taken')
                return render(request, 'reddit_users/signup.html')
            else:
                user = User.objects.create_user(
                    username=username, password=password, email=email)
                user.save()

                user_model = User.objects.get(username=username)
                reddit_user_model = RedditUser.objects.create(
                    user=user_model, id_user=user_model.id, email=email)
                reddit_user_model.save()
                messages.info(request, 'User and profile created')
                return redirect('reddit_users:login')
        else:
            messages.info(request, 'Passwords do not match')
            return render(request, 'reddit_users/signup.html')

    else:
        return render(request, 'reddit_users/signup.html')


def login(request):

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        print(user)
        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'Invalid credentials')
            return render(request, 'reddit_users/login.html')

    else:
        return render(request, 'reddit_users/login.html')


@login_required(login_url='/login/')
def logout(request):
    auth.logout(request)
    return redirect('reddit_users:index')


def search(request):
    query = request.GET.get('query')

    subreddits = Subreddit.objects.filter(name__icontains=query)
    users = User.objects.filter(username__icontains=query)
    posts = Post.objects.filter(
        Q(title__icontains=query) | Q(content__icontains=query))
    # print(f"Subreddits: {subreddits}")
    # print(f"Users: {users}")
    # print(f"Posts: {posts}")
    results = {
        'subreddits': [{'id': subreddit.id, 'name': subreddit.name} for subreddit in subreddits],
        'users': [{'username': user.username} for user in users],
        'posts': [{'id': post.id, 'title': post.title, 'author': post.author.username} for post in posts]
    }
    print(results)
    return JsonResponse(results)

reddit/reddit_users/templates/reddit_users/homepage.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="all-posts-container">
  {% if posts %}
  <h3>All Posts</h3>
  <div class="posts">
    {% for post in posts %}
    <div class="post">
      <small>
        <h2 class="subreddit-title">
          <a
            href="{% url 'subreddits:view_subreddit' post.subreddit.id %}"
            style="color: #ff4500"
            >r/{{ post.subreddit.name }}</a
          >
        </h2>
      </small>
      <small
        ><a href="{% url 'reddit_users:view_profile' post.author.username %}"
          >u/{{ post.author.username }}</a
        >
        | {{ post.created_at }}</small
      >
      <h3 class="post-title">
        <a href="{% url 'posts:view_post' post.id %}">{{ post.title }}</a>
      </h3>
      <p class="post-content">{{ post.content }}</p>
      <div class="post-footer">
        <button
          class="vote-btn upvote-btn {% if request.user in post.upvoted_by.all %}upvoted{% endif %}"
          data-post-id="{{ post.id }}"
          style="border: none; background: none; cursor: pointer; outline: none"
        >
          <i class="bi bi-arrow-up-square"></i></button
        >|
        <span id="vote-count-{{ post.id }}">{{ post.get_vote_count }}</span> |
        <button
          class="vote-btn downvote-btn {% if request.user in post.downvoted_by.all %}downvoted{% endif %}"
          data-post-id="{{ post.id }}"
          style="border: none; background: none; cursor: pointer; outline: none"
        >
          <i class="bi bi-arrow-down-square"></i>
        </button>
        |
        <a href="{% url 'posts:view_post' post.id %}">
          {{ post.comments.count }} comments
        </a>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <p>No posts yet.</p>
  {% endif %}
</div>
<div class="main-side-container">
  {% if user.is_authenticated %}
  <h3>Welcome to Reddit, {{user.username}}</h3>
  <br />
  <a href="{% url 'subreddits:create_subreddit' %}" class="custom-btn"
    >Create Subreddit +</a
  >
  {% else %}
  <h1>Welcome to Reddit</h1>
  {% endif %}
</div>
<br />
<script>
  document.querySelectorAll(".vote-btn").forEach((button) => {
    button.addEventListener("click", function () {
      const postId = this.getAttribute("data-post-id");
      const action = this.classList.contains("upvote-btn")
        ? "upvote"
        : "downvote";
      const url = "{% url 'posts:vote_post' %}";

      fetch(url, {
        method: "POST",
        headers: {
          "X-CSRFToken": "{{ csrf_token }}",
          "Content-Type": "application/x-www-form-urlencoded",
        },
        body: new URLSearchParams({ post_id: postId, action: action }),
      })
        .then((response) => response.json())
        .then((data) => {
          document.getElementById(`vote-count-${postId}`).innerText =
            data.vote_count;
          if (action === "upvote") {
            this.classList.toggle("upvoted");
            this.classList.remove("downvoted");
          } else {
            this.classList.toggle("downvoted");
            this.classList.remove("upvoted");
          }
        });
    });
  });
</script>
{% endblock %}

reddit/reddit_users/templates/reddit_users/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login - Reddit</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/login.css' %}"
    />
  </head>
  <body>
    <div class="login-container">
      <h1>Log in to Reddit</h1>
      <div class="login-error-msg">
        {% for message in messages %}
        <h4>{{ message }}</h4>
        {% endfor %}
      </div>
      <form action="" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username" required />
        <input
          type="password"
          name="password"
          placeholder="Password"
          required
        />
        <button type="submit">Log In</button>
      </form>
      <div class="signup-link">
        <p>New to Reddit? <a href="/signup">Sign Up</a></p>
      </div>
    </div>
  </body>
</html>

reddit/reddit_users/templates/reddit_users/profile.html
{% extends 'base.html' %} {% block title %}Profile of {{
profile_user.user.username }} - Reddit Clone{% endblock %} {% block content %}
<div class="profile-activity-container">
  <!-- <h2>{{ profile_user.username }}'s Profile</h2> -->
  <div class="toggle-buttons">
    <button id="show-posts" onclick="showPosts()">User Posts</button>
    <button id="show-comments" onclick="showComments()">User Comments</button>
  </div>
  <!-- posts section -->
  <div id="posts-section">
    <h3>User Posts</h3>
    <div class="posts">
      {% for post in posts %}
      <div class="post">
        <h4>
          <a href="{% url 'posts:view_post' post.id %}">{{ post.title }}</a>
        </h4>
        <p>{{ post.content|truncatewords:20 }}</p>
        <small>Posted on {{ post.created_at|date:"F j, Y, g:i a" }}</small>
      </div>
      <hr />
      {% empty %}
      <p>No posts yet.</p>
      {% endfor %}
    </div>
  </div>
  <!-- comments section -->
  <div id="comments-section" style="display: none">
    <h3>User Comments</h3>
    <div class="comments">
      {% for comment in comments %}
      <div class="comment">
        <p>{{ comment.content }}</p>
        <small
          >On post:
          <a href="{% url 'posts:view_post' comment.post.id %}"
            >{{ comment.post.title }}</a
          ></small
        >
        <small
          >Commented on {{ comment.created_at|date:"F j, Y, g:i a" }}</small
        >
      </div>
      <hr />
      {% empty %}
      <p>No comments yet.</p>
      {% endfor %}
    </div>
  </div>
</div>

<div class="profile-about-container">
  <div class="profile-username-container">
    <h4>{{ profile_user.username }}</h4>
  </div>
  {% if user.is_authenticated and user != profile_user %}
  <div class="profile-follow-container">
    {% if is_following %}
    <form
      action="{% url 'reddit_users:unfollow_user' profile_user.username %}"
      method="post"
    >
      {% csrf_token %}
      <button type="submit" class="follow-btn unfollow-btn">Unfollow</button>
    </form>
    {% else %}
    <form
      action="{% url 'reddit_users:follow_user' profile_user.username %}"
      method="post"
    >
      {% csrf_token %}
      <button type="submit" class="follow-btn">Follow</button>
    </form>
    {% endif %} {% if message in messages %}
    <p>{{ message }}</p>
    {% endif %}
  </div>
  {% endif %}
  <div class="profile-karma-container">
    <div class="comment-karma">
      <h3>{{ comment_count }}</h3>
      <small><p>Comment Karma</p></small>
    </div>
    <div class="post-karma">
      <h3>{{ post_count }}</h3>
      <small><p>Post Karma</p></small>
    </div>
    <div class="followers-karma">
      <h3>{{ follower_count }}</h3>
      <small><p>Followers</p></small>
    </div>
    <div class="following-karma">
      <h3>{{ following_count }}</h3>
      <small><p>Following</p></small>
    </div>
  </div>
</div>

<script>
  function showPosts() {
    console.log("show posts");
    let postsSection = document.getElementById("posts-section");
    let commentsSection = document.getElementById("comments-section");

    if (postsSection && commentsSection) {
      postsSection.style.display = "block";
      commentsSection.style.display = "none";
    } else {
      console.error("Elements not found");
    }
  }

  function showComments() {
    console.log("show comments");
    let postsSection = document.getElementById("posts-section");
    let commentsSection = document.getElementById("comments-section");

    if (postsSection && commentsSection) {
      postsSection.style.display = "none";
      commentsSection.style.display = "block";
    } else {
      console.error("Elements not found");
    }
  }
</script>
{% endblock %}

reddit/reddit_users/templates/reddit_users/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sign Up - Reddit</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/signup.css' %}"
    />
  </head>
  <body>
    <div class="signup-container">
      <h1>Sign Up</h1>
      <div class="signup-error-msg">
        {% for message in messages %}
        <h4>{{ message }}</h4>
        {% endfor %}
      </div>
      <form action="" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username" required />
        <input type="email" name="email" placeholder="Email" required />
        <input
          type="password"
          name="password"
          placeholder="Password"
          required
        />
        <input
          type="password"
          name="password2"
          placeholder="Confirm Password"
          required
        />
        <button type="submit">Sign Up</button>
      </form>
      <div class="login-link">
        Already have an account?
        <a href="{% url 'reddit_users:login' %}">Log In</a>
      </div>
    </div>
  </body>
</html>