reddit/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('create/', views.create_post, name='create_post'),
    path('<int:post_id>/', views.view_post, name='view_post'),
    path('edit/<int:post_id>/', views.edit_post, name='edit_post'),
    path('post/<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('vote/', views.vote_post, name='vote_post'),

]

reddit/reddit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reddit_users.urls', namespace='reddit_users')),
    path('subreddits/', include('subreddits.urls', namespace='subreddits')),
    path('posts/', include('posts.urls', namespace='posts')),
]

reddit/reddit_users/urls.py
from django.urls import path
from . import views

app_name = 'reddit_users'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<str:username>/', views.view_profile, name='view_profile'),
    path('profile/<str:username>/follow/',
         views.follow_user, name='follow_user'),
    path('profile/<str:username>/unfollow/',
         views.unfollow_user, name='unfollow_user'),
    path('search/', views.search, name='search')
]

reddit/subreddits/urls.py
from django.urls import path
from . import views

app_name = 'subreddits'

urlpatterns = [
    path('create/', views.create_subreddit, name='create_subreddit'),
    path('<int:subreddit_id>/', views.view_subreddit, name='view_subreddit')

]

reddit/subreddits/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Subreddit(models.Model):
    name = models.CharField(max_length=20, unique=True)
    description = models.TextField()
    creator = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='created_subreddits')

    def __str__(self):
        return self.name

reddit/subreddits/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import Subreddit
from django.contrib import messages


# Create your views here.

@login_required(login_url='/login/')
def create_subreddit(request):

    if request.method == 'POST':

        name = request.POST.get('name')
        description = request.POST.get('description')

        if Subreddit.objects.filter(name=name).exists():
            messages.info(request, 'Subreddit name taken')
            return render(request, 'subreddits/create_subreddit.html')

        else:
            subreddit = Subreddit.objects.create(
                name=name, description=description, creator=request.user)
            subreddit.save()
            messages.info(request, 'Subreddit created')
            return redirect('reddit_users:index')

    else:
        return render(request, 'subreddits/create_subreddit.html')


def view_subreddit(request, subreddit_id):
    subreddit = Subreddit.objects.get(id=subreddit_id)
    posts = subreddit.posts.all()
    return render(request, 'subreddits/view_subreddit.html', {'subreddit': subreddit, 'posts': posts})

reddit/subreddits/templates/subreddits/create_subreddit.html
<!-- subreddits/templates/subreddits/create_subreddit.html -->
{% extends 'base.html' %}{% load static %}{% block content %}
<!-- loading messages -->

<body>
  <div class="container">
    <h1 class="text-center my-4">Create your Subreddit</h1>
    <div class="error-msg">
      {% for message in messages %}
      <div class="alert alert-danger" role="alert">{{ message }}</div>
      {% endfor %}
    </div>
    <form action="" method="POST" class="bg-light p-4 rounded shadow-sm">
      {% csrf_token %}
      <div class="form-group">
        <label for="name">Subreddit Name</label>
        <input
          type="text"
          name="name"
          class="form-control"
          id="name"
          placeholder="Subreddit Name"
          required
        />
      </div>
      <div class="form-group">
        <label for="description">Description</label>
        <textarea
          name="description"
          class="form-control"
          id="description"
          placeholder="Description"
          rows="4"
          required
        ></textarea>
      </div>
      <button type="submit" class="btn btn-primary">Create Subreddit</button>
    </form>
  </div>
</body>
{% endblock %}

reddit/subreddits/templates/subreddits/view_subreddit.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="posts-container">
  <h2>Posts</h2>
  {% if posts %}
  <div class="posts">
    {% for post in posts %}
    <div class="post">
      <small
        ><a href="{% url 'reddit_users:view_profile' post.author.username %}"
          >u/{{ post.author.username }}</a
        >
        | {{ post.created_at }}</small
      >
      <h3 class="post-title">
        <a href="{% url 'posts:view_post' post.id %}">{{ post.title }}</a>
      </h3>
      <p>{{ post.content }}</p>
      <div class="post-footer">
        <button
          class="vote-btn upvote-btn {% if request.user in post.upvoted_by.all %}upvoted{% endif %}"
          data-post-id="{{ post.id }}"
          style="border: none; background: none; cursor: pointer; outline: none"
        >
          <i class="bi bi-arrow-up-square"></i></button
        >|
        <span id="vote-count-{{ post.id }}">{{ post.get_vote_count }}</span> |
        <button
          class="vote-btn downvote-btn {% if request.user in post.downvoted_by.all %}downvoted{% endif %}"
          data-post-id="{{ post.id }}"
          style="border: none; background: none; cursor: pointer; outline: none"
        >
          <i class="bi bi-arrow-down-square"></i>
        </button>
        |
        <a href="{% url 'posts:view_post' post.id %}">
          {{ post.comments.count }} comments
        </a>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <p>No posts yet. Be the first to create a post!</p>
  {% endif %}
</div>
<div class="about-subreddit">
  <h1>{{ subreddit.name }}</h1>
  <a
    href="{% url 'posts:create_post' %}?subreddit={{ subreddit.id }}"
    class="subreddit-btn"
    >Create Post</a
  >
  <p>{{ subreddit.description }}</p>
</div>
<script>
  document.querySelectorAll(".vote-btn").forEach((button) => {
    button.addEventListener("click", function () {
      const postId = this.getAttribute("data-post-id");
      const action = this.classList.contains("upvote-btn")
        ? "upvote"
        : "downvote";
      const url = "{% url 'posts:vote_post' %}";

      fetch(url, {
        method: "POST",
        headers: {
          "X-CSRFToken": "{{ csrf_token }}",
          "Content-Type": "application/x-www-form-urlencoded",
        },
        body: new URLSearchParams({ post_id: postId, action: action }),
      })
        .then((response) => response.json())
        .then((data) => {
          document.getElementById(`vote-count-${postId}`).innerText =
            data.vote_count;
          if (action === "upvote") {
            this.classList.toggle("upvoted");
            this.classList.remove("downvoted");
            document
              .querySelector(`.downvote-btn[data-post-id="${postId}"]`)
              .classList.remove("downvoted");
          } else {
            this.classList.toggle("downvoted");
            this.classList.remove("upvoted");
            document
              .querySelector(`.upvote-btn[data-post-id="${postId}"]`)
              .classList.remove("upvoted");
          }
        });
    });
  });
</script>
{% endblock %}